name: Sync on DOM Cloud DEV

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_DEV }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_DEV }}
          data: >-
            {
              "commands": [
                "git reset --hard",
                "git clean -fd",
                "git pull",
                "composer install --no-interaction --prefer-dist --optimize-autoloader",
                "npm install",
                "npm run build",
                "php artisan migrate --force",
                "php artisan config:cache",
                "php artisan route:cache",
                "php artisan view:cache",
                "restart"
              ]
            }

   
